// 생성된 파일 — 직접 고치지 말 것. 정본은 shared/fingerprint-words.txt,
// 생성은 `python3 tools/shared-gen/gen_words.py`.
// 목록 해시 sha256=0129031a9019f99e02724b5a43eadc35723d1b6ce459085fb8decdad5f47f99c
export const FINGERPRINT_WORDS: readonly string[] = [
  "acid", "acorn", "actor", "agent", "alarm", "album", "alien", "alley",
  "amber", "anchor", "angel", "ankle", "apple", "april", "arch", "arena",
  "armor", "arrow", "atlas", "atom", "aunt", "autumn", "axis", "bacon",
  "badge", "bagel", "baker", "balcony", "bamboo", "banana", "barn", "basil",
  "beach", "beetle", "bell", "bench", "berry", "bird", "bison", "blade",
  "blossom", "board", "bolt", "bone", "book", "bottle", "bowl", "brain",
  "bread", "brick", "broom", "brush", "bubble", "bucket", "buffalo", "bugle",
  "bulb", "bundle", "burger", "bush", "button", "cabin", "cactus", "cake",
  "camel", "candle", "captain", "card", "castle", "cedar", "cello", "cement",
  "chain", "cheese", "chicken", "cider", "cigar", "circle", "city", "clam",
  "cliff", "cloak", "coal", "cobra", "cocoa", "coffee", "coin", "comet",
  "cone", "cookie", "copper", "coral", "cotton", "couch", "crab", "cream",
  "cricket", "crown", "crystal", "cube", "curtain", "cushion", "cymbal", "dagger",
  "daisy", "dancer", "dawn", "deck", "deer", "delta", "denim", "desert",
  "diamond", "diesel", "dinner", "dish", "dock", "dolphin", "domino", "donkey",
  "dragon", "dream", "drill", "drum", "duck", "dune", "eagle", "earth",
  "echo", "elbow", "elder", "ember", "emerald", "engine", "envelope", "eraser",
  "fabric", "falcon", "farm", "feather", "fence", "fern", "fever", "fiber",
  "field", "finch", "fire", "flag", "fleet", "flint", "flour", "flute",
  "folder", "forest", "fossil", "fountain", "frame", "friend", "frost", "fruit",
  "garden", "gate", "gazelle", "gecko", "ghost", "giant", "ginger", "giraffe",
  "glacier", "globe", "goat", "golf", "gong", "goose", "grain", "grill",
  "grove", "guitar", "gulf", "hammer", "harbor", "hazel", "helmet", "hickory",
  "honey", "hornet", "hotel", "island", "ivory", "jacket", "jaguar", "jasmine",
  "jelly", "jungle", "kettle", "kitten", "ladder", "lagoon", "lantern", "laurel",
  "lemon", "lentil", "leopard", "letter", "lilac", "lime", "linen", "lion",
  "lizard", "llama", "lobby", "locket", "lodge", "lotus", "lumber", "lunar",
  "lychee", "magnet", "mango", "maple", "marble", "meadow", "melon", "mentor",
  "mercury", "meteor", "mirror", "mitten", "monkey", "moon", "mosaic", "motor",
  "mountain", "muffin", "mulberry", "mushroom", "nectar", "needle", "nest", "nickel",
  "noodle", "north", "notebook", "nutmeg", "oak", "oasis", "oatmeal", "ocean",
  "octopus", "olive", "onion", "opal", "orange", "orbit", "orchard", "organ",
];
export const FINGERPRINT_WORDS_SHA256 = "0129031a9019f99e02724b5a43eadc35723d1b6ce459085fb8decdad5f47f99c";
